platform :ios, '13.0'

inhibit_all_warnings!
use_frameworks!
def common_pods
  
  pod 'RxAlamofire'
  
  #UI
  pod "SwipeTransition"
  pod "SwipeTransitionAutoSwipeBack"
  
  #Rx
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxDataSources', '~> 5.0'
  
  #Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
end

def exceptTest
  #Lint
  pod "SwiftLint"
  
  #SwiftGen
  pod "SwiftGen"

end

target 'myRecipick' do
  common_pods
  exceptTest
end

target 'myRecipickTests' do
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
